const fs = require('fs');
const path = require('path');

const filePath = 'c:/Users/PJH/onestop-ai-custom-service/src/data/explanatory_notes/chapter_68.json';

const newEntry = {
  "hsCode": "6802",
  "titleKo": "68.02 - 가공한 석비용ㆍ건축용 석재[슬레이트(slate)는 제외한다]와 이들의 제품(제6801호의 물품은 제외한다), 모자이크 큐브와 이와 유사한 것[천연 석재의 것으로서 슬레이트(slate) 제품을 포함하며, 뒷면을 보강한 것인지에 상관없다], 인공적으로 착색한 천연 석재[슬레이트(slate)를 포함한다]의 알갱이ㆍ조각ㆍ가루",
  "titleEn": "68.02 - Worked monumental or building stone (except slate) and articles thereof, other than goods of heading 68.01; mosaic cubes and the like, of natural stone (including slate), whether or not on a backing; artificially coloured granules, chippings and powder, of natural stone (including slate).",
  "contentKo": "이 호에는 제25류의 채석장의 생산품을 더 가공하여 만든 천연의 석비용ㆍ건축용 석재[슬레이트(slate)는 제외한다]를 분류한다. 그러나 이 표의 다른 호에 열거하는 물품으로서 어떤 예외가 있는데, 이러한 예들은 이 해설 끝 부분에 이 류의 총설에 제시하고 있다.\n\n그러므로 이 호에는 분할, 거칠게 절단, 네모로 절단, 톱질에 의하여 네모로 절단(표면이 정사각형이나 직사각형)하여 단순히 블록(block)ㆍ시트(sheet)ㆍ슬래브(slab)로 조형한 것 이상의 가공을 한 석을 분류한다.\n\n따라서 이 호에는 석공ㆍ조각가 등에 의하여 다음의 모양으로 제조된 돌을 분류한다. 즉 :\n\n(A) 대충 톱질로 절단한 블랭크(blank) ; 직사각형 이외의 시트(sheet)(한 면이나 두 면 이상의 삼각형의 것ㆍ육각형의 것ㆍ사다리꼴의 것ㆍ원형 등의 것)\n\n(B) 여러 가지 모양의 돌[블록(block)ㆍ슬래브(slab)ㆍ시트(sheet)를 포함하며 완성품의 모양인지에는 상관없다]을 부조(浮彫)가공한 것(즉, 거칠게 융기된 면이 남아 있긴 하지만 언저리를 평활하게 하여 “반석(rock faced)” 모양으로 만든 석), 곡괭이ㆍ부싱해머ㆍ끌 등으로 드레스한 것, 드래그-콤(drag-comb) 등으로 이랑을 낸 것, 평평하게 한 것, 모래로 다듬은 것, 연마한 것, 광택을 낸 것, 모서리를 깎아 사면이 된(chamfered) 것, 성형한 것, 선반가공한 것, 장식한 것, 조각한 것 등\n\n그러므로 이 호에는 앞에서 설명한 가공을 한 축조용 석[외장용 슬래브(slab)를 포함한다]뿐만 아니라 다음과 같은 물품도 역시 포함한다. 층층대ㆍ코오니스(cornice)ㆍ페디먼트(pediment)ㆍ난간ㆍ초엽ㆍ지주 ; 문이나 창의 틀과 상인방돌(lintel) ; 문지방 ; 벽난로의 장식 ; 창용 문지방; 문의 계단 ; 묘석 ; 경계선용 석과 이정표ㆍ배 매는 기둥(bollard) ; 방향표시반(panoramic indicator)(에나멜칠을 한 것인지에는 상관없다) ; 보호용 주(柱)와 방호물 ; 하수구ㆍ통ㆍ우물반 ; 제분기계용 볼(ball) ; 화분 ; 기둥(column)ㆍ토대ㆍ주두(capital for column) ; 조상(彫像)ㆍ작은 조각상ㆍ대좌(pedestal) ; 높고 낮은 부조(浮彫) ; 십자가 ; 동물상 ; 접시ㆍ꽃병ㆍ컵 ; 구중약상자(cachou box) ; 장식 문방구 세트 ; 재떨이 ; 문진 ; 인조의 과실과 잎 등. 다른 재료와 결합되어 있는 석(石)으로 만든 장식적인 물품은 보석이나 모조보석이나 금 세공물품이나 은 세공물품으로서 분류할 수 있으나(제71류 해설 참조), 석재의 주요 특성을 가지고 있는 장식품은 일반적으로 이 호에 분류한다.\n\n가구(찬장ㆍ세면대ㆍ탁자 등)의 윗부분을 형성하는 슬래브(slab) 모양의 석(石)은 가구의 다른 부분과 함께 제시하고 가구의 부분품으로서 분명히 인정할 때에는 제94류에 분류하나(조립 여부에 상관없다), 단독으로 제시하는 경우에는 이 호에 분류한다.\n\n가공한 석비용ㆍ건축용 석재의 물품은 일반적으로 제2515호나 제2516호의 석(石)으로 제조되나, 슬레이트(slate) 이외의 그 밖의 천연석(예: 석영ㆍ백운석ㆍ부싯돌ㆍ동석)으로 제조되는 경우도 있다. 동석(steatite)은 예를 들면, 내열성이나 화학적 내식성이 필요한 공업용의 축조물에 사용한다(예: 복열로에 사용한다). 이것은 또한 제지용 펄프공장과 화학공장에도 사용한다.\n\n이 호에는 또한 여러 가지의 마루나 벽 등에 사용하는 대리석 등으로 조그맣게 만든 모자이크 큐브(cubes) 및 이와 유사한 물품 등도 분류한다(종이나 그 밖의 재료로 뒤를 댄 것인지에 상관없다). 그리고 또한 인공적으로 착색된 대리석이나 그 밖의 천연석재[슬레이트(slate)룰 포함한다]의 알갱이와 조각과 가루도 포함한다(예: 상점의 진열창에 사용하는 것). 그러나 가공되지 않은 자갈, 알갱이와 조각과 착색 천연모래는 제25류에 분류한다.\n\n천연석의 조각을 시멘트나 그 밖의 결합제(예: 플라스틱)로 응결시켜 만든 슬래브(slab)ㆍ타일 등과 같은 제품과 돌의 고운 가루나 알갱이를 성형과 응결시켜 만든 작은 조각상ㆍ기둥(pillar)ㆍ컵 등은 제6810호의 인조석 제품으로 분류한다.\n\n이 호에는 다음의 것도 제외한다.\n\n(a) 가공한 슬레이트(slate)와 슬레이트 제품[모자이크 큐브(cube)와 이와 유사한 물품을 제외한다](제6803호ㆍ제9609호ㆍ제9610호)\n\n(b) 용융(鎔融 : fused)현무암의 제품(제6815호)\n\n(c) 소성(燒成)한 동석(steatite)제품(제69류나 제85류)\n\n(d) 모조신변장식용품(제7117호)\n\n(e) 제91류의 물품[예: 클록(clock)ㆍ클록(clock) 케이스와 그 부분품]\n\n(f) 조명기구와 그 부분품(제9405호)\n\n(g) 돌로 만든 단추(제9606호)와 제9504호나 제9609호의 백묵(chalk)\n\n(h) 오리지널 조각과 조상(彫像)(제9703호)",
  "contentEn": "This heading covers worked natural monumental or building stone (except slate) which has undergone working beyond the stage of simple splitting, rough hewing or sawing into blocks, sheets or slabs. The monumental or building stones commonly classified here include marble, travertine, ecaussine, limestone, alabaster, granite, porphyry, syenite, basalt, sandstone, quartzite, dolomite, steatite (soapstone), etc.\n\nIt covers stone which has been further worked by masons, sculptors, etc., for example :\n(A) Blanks roughly sawn to shape; sheets cut to other than rectangular (including square) shape (triangular, hexagonal, circular, etc.).\n(B) Stone of any shape, whether or not in the form of finished articles, which has been bossed, dressed with a pick or chisel, furrowed, planed, sand dressed, ground, polished, chamfered, moulded, turned, ornamented, carved, etc.\n\nThe heading thus includes building stone (including facing slabs), stairs, cornices, pediments, balustrades, corbels, supports; door or window frames and lintels; thresholds; mantelpieces; gravestones; curbstones and boundary stones, bollards; panoramic indicators; posts and barriers; sinks, troughs, basins; flower pots; columns, bases, capitals; statues, statuettes, pedestals; high and low reliefs; crosses; animal figures; dishes, vases, cups, cacheou boxes, writing sets, paperweights, ashtrays, artificial fruit and foliage, etc. Decorative articles of stone combined with other materials are also classified here if they retain the essential character of stone.\n\nSlabs forming the tops of furniture are classified here if presented separately, but when presented with the other parts of the furniture they are classified in heading 94.03.\n\nThe heading also covers mosaic cubes and the like, of natural stone (including slate) for flooring, walls, etc., whether or not on a paper or other backing. It also includes artificially coloured granules, chippings and powder of marble or other natural stone (including slate) used, e.g., for shop window dressing.\n\nArticles made by agglomerating chippings of natural stone with cement or other binders (e.g., plastics) are classified in heading 68.10 (artificial stone).\n\nThe heading excludes :\n(a) Worked slate and articles of slate other than mosaic cubes (heading 68.03, 96.09 or 96.10).\n(b) Articles of fused basalt (heading 68.15).\n(c) Fired steatite articles (Chapter 69 or 85).\n(d) Imitation jewellery (heading 71.17).\n(e) Clocks, clock cases and parts thereof (heading 91.12 or 91.13).\n(f) Luminaires and lighting fittings and parts thereof (heading 94.05).\n(g) Stone buttons (heading 96.06) and chalks of heading 95.04 or 96.09.\n(h) Original sculptures and statuary (heading 97.03)."
};

try {
  let fileContent = '[]';
  if (fs.existsSync(filePath)) {
    fileContent = fs.readFileSync(filePath, 'utf8');
  }
  const data = JSON.parse(fileContent);
  data.push(newEntry);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log("✅ Successfully appended 68.02 to chapter_68.json!");
} catch (e) {
  console.error("❌ Error appending to file:", e.message);
}
