const fs = require('fs');
const path = require('path');

const filePath = 'c:/Users/PJH/onestop-ai-custom-service/src/data/explanatory_notes/chapter_64.json';

const newEntry = {
  "hsCode": "6406",
  "titleKo": "64.06 - 신발류 부분품[갑피(甲皮)(바깥 바닥을 제외한 바닥에 부착한 것인지에 상관없다)를 포함한다], 갈아 끼울 수 있는 안창과 힐쿠션(heel cushion)이나 이와 유사한 물품, 각반ㆍ레깅스나 이와 유사한 물품과 이들의 부분품",
  "titleEn": "64.06 - Parts of footwear (including uppers whether or not attached to soles other than outer soles); removable in-soles, heel cushions and similar articles; gaiters, leggings and similar articles, and parts thereof.",
  "contentKo": "(Ⅰ) 신발의 부분품[갑피(甲皮)(바깥바닥을 제외한 바닥에 부착한 것인지에 상관없다)]\n갈아 끼울 수 있는 안창과 힐쿠션이나 이와 유사한 물품\n이 호에는 다음의 것을 분류한다.\n\n(A) 신발의 여러 가지 구성 부분품 : 이들 부분품들은 석면(asbestos)을 제외한 어떠한 재료로 만들어질 수있다.\n신발의 부분품은 제조하고자 하는 신발의 특징이나 형태에 따라서 그 모양을 달리하는 경우도 있으며 다음의 것을 포함한다.\n(1) 갑피(甲皮)의 부분품[예: 뱀프(vamp)ㆍ토캡(toe-cap)ㆍ쿼터(quarter)ㆍ레그(leg)ㆍ라이닝(lining)ㆍ클록스트랩(clog strap)] : 거의 갑피(甲皮) 모양으로 자른 신발제조용 가죽조각을 포함한다.\n(2) 보강재 : 이들은 쿼터(quarter)와 라이닝(lining) 사이에나 토캡(toecap)과 라이닝(lining) 사이에 삽입되는데 이와 같은 신발의 부분에 강인성과 견고성을 준다.\n(3) 안창ㆍ중창ㆍ바깥창[반창(half sole)이나 패틴(patin)을 포함한다] ; 안창의 표면에 아교로 부착하기 위한 안창(in-sole)\n(4) 아취 서포트(arch support)나 생크(shank)나 생크피스(shank piece)(보통 목제ㆍ가죽ㆍ섬유판이나 플라스틱으로 만든 것) : 신발의 굽은 아치(arch)가 형성되도록 바닥에 결합하기 위한 것이다.\n(5) 목재ㆍ고무 등으로 만든 여러 가지 형태의 뒷굽(아교ㆍ못ㆍ스크루식의 뒷굽을 포함한다) ; 뒷굽의 부분품[예: 톱피스(top piece)]\n(6) 스포츠 신발용 스터드ㆍ스파이크 등\n(7) 제6401호부터 제6405호까지에 설명된 신발로 되어있지 않거나 본질적인 특성을 갖추지 않은 부분품의 조립물[예: 안창(inner-sole)에 부착하거나 부착하지 않은 갑피(甲皮)]\n\n(B) 신발 안쪽에 부착하는 다음과 같은 부착물(석면을 제외한 어떤 재료든지 상관없다) : 즉, 갈아 낄 수 있는 안창ㆍ호스 프로텍터(hose protector)(고무나 고무가공한 직물로 만든 것 등)와 갈아 낄 수 있는 내부 힐쿠션(interior heel cushion)\n\n(II) 각반ㆍ레깅스나 이와 유사한 물품과 이들의 부분품\n이들 물품은 다리의 전부나 일부를 덮도록 되었거나, 경우에 따라서 발의 일부(예: 발목과 발 등)를 덮도록 제작되었다. 그러나 이들 물품은 발을 완전히 덮고 있지 않으므로 양말이나 스타킹과는 다르다.\n이러한 물품들은 석면 이외의 여러 가지 재료[가죽ㆍ캔버스ㆍ펠트(felt)ㆍ메리야스 편물이나 뜨개질 편물의 것 등]로 만들 수있다.\n이러한 물품에는 각반ㆍ정강이 덥개(leggings)ㆍ스패츠(spats)ㆍ감는 각반ㆍ발 부분이 없는 “마운팅 스타킹(mountain stockings)”, 레그워머(leg warmer)와 이와 유사한 물품이 있다.\n이러한 물품 중 어떤 것은 발의 장심(arch)부분 아래에 붙이는 지지용 끝이나 탄력이 있는 띠를 가지고 있는 것도 있다.\n이 호에는 앞에서 설명한 물품의 부분품으로서 명백히 인정할 수 있는 것을 포함한다.\n\n*\n* *\n이 호에는 또한 다음의 것을 제외한다.\n(a) 가죽이나 콤퍼지션레더(composition leather)(제4205호)ㆍ플라스틱(제39류)ㆍ고무(제40류)로 만든 길이 방향의 대다리(welt)\n(b) 무릎과 발목 지지물(단순히 약한 관절을 지지하거나 유지하기 위하여 만든 것과 같은 것) ; 이러한 물품은 그 구성 재료에 따라 각각의 해당하는 호에 분류한다.\n(c) 유아용의 원피스 레깅스[타이츠(tights)] ; 이들 물품은 허리까지 올라오고 다리에 꼭 맞으며 때로는 발 전체를 덮는 의류이다(제61류나 제62류).\n(d) 석면으로 만든 신발 부분품과 부속품(제6812호)\n(e) 치수별로 만든 발의 장심받침용 특수 안창과 정형외과용의 기구류(제9021호)\n(f) 스포츠 활동용의 크리켓 패드(cricket pad)ㆍ경보호구ㆍ무릎받이ㆍ그 밖의 보호용 물품(제9506호)\n(g) 나무못(peg)ㆍ못ㆍ아일릿(eyelet)ㆍ훅(hook)ㆍ버클(buckle)ㆍ프로텍터ㆍ끈ㆍ폼퐁(pompon)ㆍ레이스(각각의 해당하는 호에 분류한다), 단추ㆍ스냅파스너(snap-fastener)ㆍ프레스터드(press-stud)ㆍ푸쉬버튼(push-button)(제9606호), 슬라이드파스너(slide fastener)(지퍼)(제9607호)",
  "contentEn": "(I) Parts of footwear (including uppers whether or not attached to soles other than outer soles); removable in-soles, heel cushions and similar articles.\nSubject to Note 2 to this Chapter, this heading covers :\n(A) The various constituent parts of footwear; these parts may be of any material (except asbestos).\n(1) Uppers, and parts thereof (e.g., vamps, toe-caps, quarters, legs, linings, clog straps).\n(2) Reinforcements (stiffeners).\n(3) Inner soles, midsoles and outer soles.\n(4) Arch supports or shanks and shank pieces.\n(5) Heels of wood, rubber, etc.; parts of heels (e.g., top pieces).\n(6) Studs, spikes, etc., for sports footwear.\n(7) Assemblies of parts not yet constituting footwear.\n(B) Fittings worn inside footwear: removable in-soles, hose protectors and removable interior heel cushions.\n\n(II) Gaiters, leggings and similar articles, and parts thereof.\nThese articles are designed to cover the whole or part of the leg, and in some cases part of the foot (e.g., the ankle and instep). They differ from socks and stockings, however, in that they do not cover the foot completely.\nThey may be made of any material (leather, canvas, felt, knitted or crocheted fabrics, etc.) except asbestos.\nThese articles include gaiters, leggings, spats, puttees, \"mountain stockings\" without feet, leg warmers and similar articles.\nThis heading also covers identifiable parts of the articles described above.\n\nThe heading also excludes :\n(a) Welts of leather or composition leather (heading 42.05), of plastics (heading 39.26) or of rubber (heading 40.08).\n(b) Knee-caps and ankle-supports.\n(c) One-piece leggings (tights) for babies.\n(d) Parts and accessories of asbestos (heading 68.12).\n(e) Special arch supports made to measure, and orthopaedic appliances (heading 90.21).\n(f) Cricket pads, shin-guards and other protective sports gear (heading 95.06).\n(g) Pegs, nails, eyelets, hooks, buckles, protectors, laces, pompons (classified in their appropriate headings), buttons (heading 96.06), slide fasteners (heading 96.07)."
};

try {
  let fileContent = '[]';
  if (fs.existsSync(filePath)) {
    fileContent = fs.readFileSync(filePath, 'utf8');
  }
  const data = JSON.parse(fileContent);
  data.push(newEntry);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log("✅ Successfully appended 64.06 to chapter_64.json!");
} catch (e) {
  console.error("❌ Error appending to file:", e.message);
}
