const fs = require('fs');
const path = require('path');

const filePath = 'c:/Users/PJH/onestop-ai-custom-service/src/data/explanatory_notes/chapter_68.json';

const newEntry = {
  "hsCode": "6812",
  "titleKo": "68.12 - 가공한 석면섬유, 석면을 기본 재료로 한 혼합물, 석면과 탄산마그네슘을 기본 재료로 한 혼합물, 그 혼합물들의 제품, 석면제품[예: 석면의 실ㆍ직물ㆍ의류ㆍ모자ㆍ신발ㆍ개스킷(gasket)](보강한 것인지에 상관없으며 제6811호와 제6813호의 물품은 제외한다)",
  "titleEn": "68.12 - Fabricated asbestos fibres; mixtures with a basis of asbestos or with a basis of asbestos and magnesium carbonate; articles of such mixtures or of asbestos (for example, thread, woven fabric, clothing, headgear, footwear, gaskets), whether or not reinforced, other than goods of heading 68.11 or 68.13.",
  "contentKo": "이 호에는 두들겨 펴거나, 세정ㆍ선별ㆍ등급선별의 가공보다 훨씬 더 가공한 석면섬유[예: 카드(card)한 섬유, 염색한 섬유]를 분류한다. 이것은 어떠한 용도(예: 방직용ㆍ펠트용 등이나 여과용ㆍ절연용ㆍ포장용 등의 재료)로 사용하는지에 상관없다. 조(粗)석면섬유ㆍ길이에 따라 단순히 등급이 매겨진 것ㆍ두들겨 편 것이나 세정한 석면섬유는 이 호에 제외한다(제2524호).\n\n이 호에는 또한 탄산마그네슘ㆍ셀룰로오스파이버ㆍ톱밥ㆍ부석ㆍ활석ㆍ플라스틱ㆍ규산질토ㆍ슬래그(slag)ㆍ산화알루미늄ㆍ유리섬유ㆍ코르크(cork) 등과 석면의 혼합물을 포함하며, 열절연용의 포장재료ㆍ여과용 재료ㆍ성형용 석면제품의 기본재료로 사용한다.\n\n그러나 특히 이 호에는 앞 항에서와 같이 단일ㆍ혼합된 석면의 제품을 분류하며, 때로는 천연수지ㆍ플라스틱ㆍ규산소다ㆍ아스팔트ㆍ고무 등을 혼합하는 경우도 있다. 이들 제품은 펠팅(felting)ㆍ방적ㆍ꼬임ㆍ편조ㆍ제직ㆍ조합ㆍ성형하여 제조하는 경우도 있다.\n\n청석면(crocidolite asbestos)에 대한 설명은 제2524호에 대한 해설 참조.\n\n석면 종이ㆍ판지ㆍ펠트(felt)는 석면시멘트의 시트(sheet)(제6811호)를 제조할 때와 마찬가지로 석면섬유를 분해하여 펄프 모양으로 만들고 이것을 성형ㆍ압축하여 시트(sheet) 모양으로 제조한 것이다. 보드는 플라스틱과 석면 시트(sheet)의 겹붙인 층을 접착하여 제조한다. 이들 제품은 사용한 각각의 석면섬유가 쉽게 식별될 수 있다는 점에서 제6811호의 물품과는 구별된다. 이들 물품은 코일 모양ㆍ시트(sheet) 모양ㆍ플레이트(plate)나 스트립(strip) ㆍ프레임(frame)ㆍ디스크(disc)ㆍ링(ring) 등의 모양으로 절단되어 있는 경우도 있다.\n\n단사나 복합사의 제조는 석면섬유를 두들겨 펴거나 카드(card)한 다음에 방적한다. 석면섬유는 신축성이 없으며, 장섬유는 방적용으로 사용하고 단섬유는 판지ㆍ펠트(felt)ㆍ종이ㆍ석면시멘트ㆍ석면 가루의 제조에 사용한다.\n\n이 호의 그 밖의 석면제품에는 끈(cord)ㆍ플레이트(plate)ㆍ패드(pad) ; 피스(piece)ㆍ특정 모양으로 절단한 직물 ; 스트립(strip)ㆍ덮개ㆍ관ㆍ도관ㆍ관(管)용의 조인트(joint) ; 용기 ; 막대(rod)ㆍ슬래브(slab)ㆍ타일 ; 포장용 조인트(joint)[제8484호의 금속과 석면으로 만든 개스킷(gasket)과 이와 유사한 조인트(joint)나 개스킷(gasket)과 조인트(joint)의 세트는 제외한다] ; 필터 블록(filter block) ; 테이블 매트 ; 소방수용ㆍ공업용ㆍ화학ㆍ그 밖의 종업원용 등의 보호용 의류ㆍ모자나 신발 등[예: 상의ㆍ바지ㆍ앞치마ㆍ소매ㆍ장갑ㆍ벙어리장갑ㆍ각반ㆍ보통 운모제의 접안경을 접착한 후드(hood)와 마스크ㆍ헬멧ㆍ갑피(甲皮)나 바닥이 석면으로 만든 장화] ; 매트리스 ; 소방수용의 보호물ㆍ소화용의 시트(sheet)ㆍ극장용의 커튼ㆍ가스의 본관 중에서 방화용으로 석면을 피복시킨 철제의 구(sphere)와 원추(cone)를 포함한다.\n\n이러한 모든 제품은 금속(간혹 황동이나 아연의 선)이나 그 밖의 재료(예: 방직용 섬유나 유리섬유)로서 보강한 경우도 있으며 ; 그리스ㆍ활석ㆍ혹연ㆍ고무를 도포(塗布)하거나 니스칠한 것ㆍ청동색을 만든 것ㆍ전체를 착색한 것ㆍ연마한 것ㆍ천공(穿孔)한 것ㆍ절삭한 것ㆍ그 밖의 가공을 한 것도 있다.\n\n이 호에는 총설에서 제외한 것에 추가해서 다음의 것도 제외한다.\n(a) 석면의 가루나 플레이크(flake)(제2524호)\n(b) 충전물로서 석면을 함유하고 있어도 주로 플라스틱으로 만든 재료와 제품(제39류)\n(c) 석면시멘트(asbestos-cement)제품(제6811호)\n(d) 석면을 기본재료로 하여 만든 마찰재료(제6813호)",
  "contentEn": "This heading covers asbestos fibres which have been processed beyond simple opening, cleaning and sorting (e.g., carded or dyed fibres), regardless of their intended use (textiles, felting, filtering, insulating, packing, etc.). Raw asbestos fibres, simply graded by length, opened or washed are excluded (heading 25.24).\n\nThe heading also covers mixtures of asbestos with other substances (magnesium carbonate, cellulose fibres, sawdust, pumice, talc, plastics, siliceous earths, slag, alumina, glass fibres, cork, etc.) used as heat-insulating packing, filtering materials or as bases for moulded asbestos articles.\n\nIn addition, the heading covers articles made of single or mixed asbestos, whether or not combined with resins, plastics, sodium silicate, asphalt, rubber, etc. These articles may be obtained by felting, spinning, twisting, braiding, weaving, assembling or moulding.\n\nFor a description of crocidolite asbestos, see Explanatory Note to heading 25.24.\n\nAsbestos paper, paperboard and felt are made by reducing asbestos fibres to a pulp and forming sheets, similar to asbestos-cement sheets (heading 68.11). Boards are made by gluing together laminated layers of plastic and asbestos sheets. These products are distinguished from heading 68.11 articles by the fact that the individual asbestos fibres are easily identifiable. They may be cut into coils, sheets, plates, strips, frames, discs, rings, etc.\n\nSingle or multiple yarns are made by spinning opened or carded asbestos fibres. Long fibres are used for spinning, while short fibres are used for paperboard, felt, paper, asbestos-cement and asbestos powder.\n\nOther asbestos articles include cords, plates, pads; pieces or shape-cut fabrics; strips, sleeves, pipes, conduits, joints; containers; rods, slabs, tiles; packing joints (except gaskets of heading 84.84); filter blocks; table mats; protective clothing, headgear and footwear (e.g., coats, trousers, aprons, sleeves, gloves, mittens, gaiters, hoods and masks, helmets, boots); mattresses; firemen's shields, extinguishing sheets, theater curtains; and iron spheres or cones coated with asbestos for fire protection in gas mains.\n\nAll these articles may be reinforced with metal (brass or zinc wire) or other materials (textile or glass fibres), or coated, varnished, bronzed, coloured, ground, perforated, cut or otherwise worked.\n\nThe heading excludes :\n(a) Asbestos powder or flakes (heading 25.24).\n(b) Materials and articles mainly of plastics, even if containing asbestos as filler (Chapter 39).\n(c) Articles of asbestos-cement (heading 68.11).\n(d) Friction materials based on asbestos (heading 68.13)."
};

try {
  let fileContent = '[]';
  if (fs.existsSync(filePath)) {
    fileContent = fs.readFileSync(filePath, 'utf8');
  }
  const data = JSON.parse(fileContent);
  data.push(newEntry);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log("✅ Successfully appended 68.12 to chapter_68.json!");
} catch (e) {
  console.error("❌ Error appending to file:", e.message);
}
